#scheduler-config
cron:0 0 4 1/1 * ? *

#sftp-config
sftp.host=16.171.66.233
sftp.port=22
sftp.identityFile=keys/private-key.pem
sftp.targetPath=target/
sftp.errorPath=error/
sftp.source=source/

#jms-config
jms.brocker.url=ssl://b-ed947dc4-8a6e-4ac2-af34-afa47d97df34-1.mq.eu-north-1.amazonaws.com:61617
jms.user=mule-amq
jms.maxRedelivery=-1
jms.errorQueue=failedErrorQueue
jms.validQueue=failedValidQueue

#vm-config
vm.max.outstanding=0
vm.queue=reprocess
vm.errorQueue=reprocessError

#smtp-config
smtp.host=smtp.gmail.com
smtp.user=abhithaisu@gmail.com
smtp.port=587
smtp.receiver=abhithaisu@gmail.com

#general-config
connectionTimeout=10000
responseTimeout=45000
readTimeout=10000
writeTimeout=10000

#retry-logic
retry.attempt=2
retry.frequency=10000

#os-config
os.entryTtl=24

#batch-config
batch.blockSize=20000
batch.maxFailed=-1
batch.concurrency=1